localstatedir = "/usr/local/var/lib/glusterd2"
logdir = "/usr/local/var/log/glusterd2"
logfile = "glusterd2.log"
rundir = "/usr/local/var/run/glusterd2"
peeraddress = ":24008"
clientaddress = ":24007"
